### ISSUE TITLE
Worked on ost from 2012 and 2013, but had a hiccough on ost from 2017

### ISSUE THREAD

**Issue by Barkfin** [mkorthof/ost2pst#2] opened 2018-11-04 09:02 UTC
```
OST2PST (180915)

INFO: Loading OST file 2017.ost (1GB)
INFO: Folder 0 Root - Public
INFO: Folder 1 Root - Mailbox
INFO: Converting 2017.ost to 2017.pst - 1336MB/1336MB (100%)
Exception in thread "Thread-0" class com.aspose.email.system.exceptions.NotImplementedException: The method or operation is not implemented
com.aspose.email.akm$b.a(SourceFile:3925)
com.aspose.email.akm.a(SourceFile:824)
com.aspose.email.akm.a(SourceFile:620)
com.aspose.email.wk.b(SourceFile:349)
com.aspose.email.acy.a(SourceFile:1774)
com.aspose.email.acy.b(SourceFile:733)
com.aspose.email.ape.a(SourceFile:893)
com.aspose.email.ape.b(SourceFile:1192)
com.aspose.email.PersonalStorage.convertTo(SourceFile:540)
com.aspose.email.PersonalStorage.saveAs(SourceFile:454)
com.ost2pst.LoadAndConvertOSTFileCLI$1.run(LoadAndConvertOSTFileCLI.java:70)
java.lang.Thread.run(Unknown Source)
        at com.aspose.email.akm$b.a(SourceFile:3925)
        at com.aspose.email.akm.a(SourceFile:824)
        at com.aspose.email.akm.a(SourceFile:620)
        at com.aspose.email.wk.b(SourceFile:349)
        at com.aspose.email.acy.a(SourceFile:1774)
        at com.aspose.email.acy.b(SourceFile:733)
        at com.aspose.email.ape.a(SourceFile:893)
        at com.aspose.email.ape.b(SourceFile:1192)
        at com.aspose.email.PersonalStorage.convertTo(SourceFile:540)
        at com.aspose.email.PersonalStorage.saveAs(SourceFile:454)
        at com.ost2pst.LoadAndConvertOSTFileCLI$1.run(LoadAndConvertOSTFileCLI.java:70)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by Dev-iL** [comment] 2019-06-06 11:03
This is a duplicate of a closed issue (#1). There's nothing the developer of this tool can do about it, since it's an issue with the Aspose.Email library, which simply doesn't support writing 2016 `.pst` files. 

There may be [some workarounds](https://forum.aspose.com/t/exception-during-ost-2013-convert/20801/2), but they require fiddling with the Aspose library.

**Closed as completed** 2019-06-22 19:11 UTC

**Comment by sskras** [comment] 2020-04-07 07:39
@Dev-iL, I am interested in possible workarounds, but the forum topic you give contains none of them, it seems.

**Comment by Dev-iL** [comment] 2020-04-07 09:37
@sskras I, too, am still interested in this. The "workaround" I was referring to was mentioned in the moderator's (developer's) reply - "_You may read the OST with your code and convert it to PST by parsing all its folders_". Unfortunately, as you said, there are no specific clues as to how to do what the Aspose developer suggested. :\

**Comment by mkorthof** [comment] 2020-04-09 08:12
@sskras @Dev-iL There are no workarounds. OST2PST does indeed show the folder list but it simply cannot not write '13/'16 format to file. Latest version warns about it, quits and wont show stack trace.
