### ISSUE TITLE
Saving to Outlook 2013/2016 PST files is not supported

### ISSUE THREAD

**Issue by arezd** [mkorthof/ost2pst#6] opened 2020-10-31 13:53 UTC
Thanks for this. Sounds like a great tool.
However, I got the following error: Saving to Outlook 2013/2016 PST files is not supported?
Any idea how to solve it?

**Comment by mkorthof** [comment] 2020-11-03 08:56
duplicate of (all) other issues #1 #2 #3 #4

**Closed as completed by mkorthof** 2020-11-03 08:56 UTC
Labels: duplicate
